server:
  port: 5000
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4Fy7cNfAgoCbKSrBhPpB
    access-key-secret: xs3ezhZkEQlX49Lj53UvthdhvOkoKc
    bucket-domain: http://test201027.oss-cn-hangzhou.aliyuncs.com
    bucket-name: test201027
    end-point: http://oss-cn-hangzhou.aliyuncs.com